load("//tests:extensions.bzl", "ext_test")

ext_test(
   name = "serialization_test",
   srcs = ["serialization_test.cpp"],
   deps = [
      "//tests/samples:serialization_samples",
      "@com_github_zeux_pugixml//:lib_pugixml",
   ],
)
