load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "com_test",
    srcs = ["com_test.cpp"],
    deps = [
        "//test:test_main",
    ],
)

cc_test(
    name = "dependency_injection_test",
    srcs = ["dependency_injection_test.cpp"],
    deps = [
        "//test:test_main",
    ],
)
