load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "constructor_traits_details_test",
    srcs = ["constructor_traits_details_test.cpp"],
    deps = [
        "//tests:test_main",
    ],
)
