load("//tests:extensions.bzl", "ext_test")

ext_test(
    name = "dependency_injection_test",
    srcs = ["dependency_injection_test.cpp"],
)

ext_test(
    name = "dispatcher_test",
    srcs = ["dispatcher_test.cpp"],
)

ext_test(
    name = "tracer_test",
    srcs = ["tracer_test.cpp"],
)
