load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "dependency_injection_test",
    srcs = ["dependency_injection_test.cpp"],
    deps = [
        "//tests:test_main",
    ],
)

cc_test(
    name = "dispatcher_test",
    srcs = ["dispatcher_test.cpp"],
    deps = [
        "//tests:test_main",
    ],
)

cc_test(
    name = "tracer_test",
    srcs = ["tracer_test.cpp"],
    deps = [
        "//tests:test_main",
    ],
)
