load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "channel_test",
    srcs = ["channel_test.cpp"],
    deps = [
        "//tests:test_main",
    ],
)

cc_test(
    name = "event_test",
    srcs = ["event_test.cpp"],
    deps = [
        "//tests:test_main",
    ],
)

cc_test(
    name = "scheduler_test",
    srcs = ["scheduler_test.cpp"],
    deps = [
        "//tests:test_main",
    ],
)

cc_test(
    name = "stop_token_test",
    srcs = ["stop_token_test.cpp"],
    deps = [
        "//tests:test_main",
    ],
)

cc_test(
    name = "thread_pool_test",
    srcs = ["thread_pool_test.cpp"],
    deps = [
        "//tests:test_main",
    ],
)

cc_test(
    name = "thread_test",
    srcs = ["thread_test.cpp"],
    deps = [
        "//tests:test_main",
    ],
)
