load("//tests:extensions.bzl", "ext_test")

ext_test(
    name = "channel_test",
    srcs = ["channel_test.cpp"],
)

ext_test(
    name = "event_test",
    srcs = ["event_test.cpp"],
)

ext_test(
    name = "scheduler_test",
    srcs = ["scheduler_test.cpp"],
)

ext_test(
    name = "stop_token_test",
    srcs = ["stop_token_test.cpp"],
)

ext_test(
    name = "thread_pool_test",
    srcs = ["thread_pool_test.cpp"],
)

ext_test(
    name = "thread_test",
    srcs = ["thread_test.cpp"],
)
